//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagirovLanguage1
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientService = new HashSet<ClientService>();
            this.Tag = new HashSet<Tag>();
        }

        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string GenderCode { get; set; }
        public string Phone { get; set; }
        public string PhotoPath { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Email { get; set; }
        public System.DateTime RegistrationDate { get; set; }

        public string GenderName
        {
            get
            {
                if (Gender == null)
                    return "";
                return Gender.Name;
            }
        }

        public string BirthdayString
        {
            get
            {
                return Birthday.ToShortDateString();
            }
        }

        public string RegistrationDateString
        {
            get
            {
                return RegistrationDate.ToShortDateString();
            }
        }

        public int VisitCount
        {
            get
            {
                return ClientService.Count;
            }
        }

        public DateTime? LastVisitDate
        {
            get
            {
                if (ClientService.Count == 0)
                    return null;
                return ClientService.Max(x => x.StartTime);
            }
        }

        public string LastVisitDateString
        {
            get
            {
                if (LastVisitDate == null)
                    return "";
                return LastVisitDate.Value.ToShortDateString();
            }
        }

        public string PhotoFullPath
        {
            get
            {
                string normalizedPhotoPath = (PhotoPath ?? "").Trim().Replace("/", "\\");
                string fileName = string.IsNullOrWhiteSpace(normalizedPhotoPath)
                    ? "picture.png"
                    : normalizedPhotoPath.Split('\\').Last();

                string path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Клиенты", fileName);

                if (!File.Exists(path))
                    path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "images", "picture.png");

                return path;
            }
        }

        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tag { get; set; }
    }
}
